apiVersion: v1
kind: Service
metadata:
  name: nft-bridge-service
spec:
  selector:
    app: nft-bridge
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  type: {{ .Values.service.type }}
